"""The generative engine — a monthly discrete-time hazard process.

The rule this module exists to honour: nothing is generated by taking a set of
features and bolting a default flag onto them with a rule. Accounts live through
months, and in each month a hazard decides what happens next. That is the same
frame the platform later FITS, so when Helios recovers a coefficient it recovers
something that genuinely produced the data.

Three things make the result defensible rather than decorative:

1. The macro path `z_t` is REAL HISTORY, pulled from FRED. Any macro sensitivity
   the platform estimates is a sensitivity that actually existed. The 2020 spike
   is not drawn in; it falls out of unemployment going to 14.8%.

2. There is an account-level FRAILTY term. Borrower quality is partly
   unobserved, so the data is not fully explainable and AUC lands in a credible
   band instead of at 0.97.

3. Default is reached through a DELINQUENCY CHAIN, not drawn directly. An
   account rolls 30 -> 60 -> 90 and either cures or rolls again. The target
   definition is then a real definition ("90+ DPD"), `delinquency_bucket` carries
   real information, and the observed default rate is an emergent property.

Competing risks — prepayment, maturity — are drawn alongside default, and the
account stops at the first terminal event.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from ..mev.panel import panel_for
from .copula import build_correlation, draw
from .portfolios import CRE_NOI_BETA
from .spec import PortfolioSpec

PANEL_START = "2015-01-01"
PANEL_END = "2025-12-01"

# Columns that exist only because we generated the data. They are the answer key,
# never part of the shipped tape, and `assemble.py` strips them.
TRUTH_COLS = ("_truth_roll_hazard",)


def _sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.clip(x, -30, 30)))


def _zstats(a: np.ndarray) -> tuple[float, float]:
    mu = float(np.mean(a))
    sd = float(np.std(a))
    return mu, (sd if sd > 1e-9 else 1.0)


def seasoning_curve(age: np.ndarray, peak: float, height: float,
                    decay: float) -> np.ndarray:
    """A seasoning hump: risk builds after origination, peaks, then decays.

    Every retail book has one, and leaving it out is a fast way for a validator to
    spot a toy model. A smooth log-normal-shaped hump in log-odds space, less a
    slow decay that represents the book burning down to its better survivors.
    """
    a = np.maximum(age, 0.5)
    return height * np.exp(-((np.log(a) - np.log(peak)) ** 2) / 0.9) - decay * np.sqrt(a)


@dataclass
class GenerationResult:
    panel: pd.DataFrame
    accounts: pd.DataFrame
    spec: PortfolioSpec
    mev_z: pd.DataFrame = field(default_factory=pd.DataFrame)


def generate(spec: PortfolioSpec, seed: int = 20260819,
             start: str = PANEL_START, end: str = PANEL_END) -> GenerationResult:
    rng = np.random.default_rng(seed)
    months = pd.date_range(start, end, freq="MS")
    n = spec.n_accounts

    # ── macro: real history, standardized over the panel window ──────────────
    need = sorted(set(spec.mev_keys) | {"hpi", "cre_price_index", "unemployment_rate",
                                        "mortgage_rate"})
    mev_raw = panel_for(need, start="2000-01-01", end=end).ffill().bfill()
    win = mev_raw.loc[(mev_raw.index >= months[0]) & (mev_raw.index <= months[-1])]
    mu, sd = win.mean(), win.std(ddof=0).replace(0, 1.0)
    mev_z = (mev_raw - mu) / sd
    lvl = {c: mev_raw[c].to_numpy(float) for c in mev_raw.columns}
    zed = {c: mev_z[c].to_numpy(float) for c in mev_raw.columns}
    midx = {d: i for i, d in enumerate(mev_raw.index)}

    # ── origination: spread across vintages so the book is seasoned ──────────
    max_term = int(max(spec.term_choices))
    first_orig = pd.Timestamp(start) - pd.DateOffset(months=min(max_term, 180))
    choices = pd.date_range(first_orig, pd.Timestamp(end) - pd.DateOffset(months=3),
                            freq="MS")
    w = np.linspace(0.45, 1.0, len(choices)) ** 1.4          # books grow over time
    orig_date = choices[rng.choice(len(choices), size=n, p=w / w.sum())]

    # ── static attributes, correlated through the copula ─────────────────────
    names = [m.name for m in spec.marginals]
    attrs = draw(n, spec.marginals, build_correlation(names, spec.correlations), rng)

    # State is a PROPERTY of the metro, not an independent draw. Generating them
    # separately would put loans in "Miami, Ohio".
    if "msa" in attrs:
        from .portfolios import MSA_STATE
        attrs["state"] = np.array([MSA_STATE.get(m, "??") for m in attrs["msa"]],
                                  dtype=object)

    term = rng.choice(np.asarray(spec.term_choices), size=n,
                      p=np.asarray(spec.term_probs)).astype(np.int32)
    if spec.key == "mortgage":
        term = np.where(attrs["product"] == "15yr fixed", 180, 360).astype(np.int32)

    rate = np.full(n, spec.rate_base, dtype=float)
    if "fico_orig" in attrs and spec.rate_fico_slope:
        rate += spec.rate_fico_slope * (attrs["fico_orig"] - 700.0) / 100.0
    if spec.key == "cre":
        rate += 0.004 * (attrs["risk_rating"] - 5.0)
    rate = np.clip(rate + rng.normal(0, 0.006, n), 0.018, 0.32)

    if spec.key == "cre":
        committed = attrs["committed_amount"].astype(float)
        is_rev = attrs["facility_type"] == "revolver"
        util0 = np.where(is_rev, rng.beta(4.0, 2.2, n), 1.0)
        orig_balance = committed * util0
    else:
        orig_balance = attrs["original_balance"].astype(float)
        committed = orig_balance.copy()
        is_rev = np.zeros(n, dtype=bool)
        util0 = np.ones(n)

    r_m = rate / 12.0
    pay = orig_balance * r_m / (1.0 - (1.0 + r_m) ** (-term.astype(float)))

    # ── per-account state ────────────────────────────────────────────────────
    st: dict[str, np.ndarray] = {
        "current_balance": orig_balance.copy(),
        "drawn": orig_balance.copy(),
        "committed": committed,
        "util": util0.astype(float),
        "delinq": np.zeros(n, dtype=np.int8),
        "alive": np.zeros(n, dtype=bool),
        "mob": np.zeros(n, dtype=np.int32),
    }
    # An account whose whole term ran out BEFORE the panel window opens never
    # appears. Without this the tape would carry loans that matured in 2012.
    orig_i = np.array([midx.get(d, -1) for d in orig_date], dtype=np.int64)
    start_i = midx[months[0]]
    done = (orig_i + term) < start_i
    st["done"] = done.copy()

    frailty = rng.normal(0.0, spec.frailty_sd, n)

    if spec.key == "mortgage":
        st["property_value"] = orig_balance / (attrs["original_ltv"] / 100.0)
        st["hpi_at_orig"] = lvl["hpi"][np.clip(orig_i, 0, None)]
        st["second_lien_pct"] = attrs["second_lien_pct"].astype(float)
    if spec.key == "cre":
        st["property_value"] = orig_balance / (attrs["original_ltv"] / 100.0)
        st["cre_index_at_orig"] = lvl["cre_price_index"][np.clip(orig_i, 0, None)]
        st["noi"] = attrs["noi"].astype(float)
        st["noi_beta"] = np.array([CRE_NOI_BETA[p] for p in attrs["property_type"]])
        st["annual_debt_service"] = attrs["noi"] / np.maximum(attrs["dscr_orig"], 0.05)
        st["dscr_at_orig"] = attrs["dscr_orig"].astype(float)
        # a persistent per-facility reporting bias, not fresh noise each month —
        # a servicer that reports optimistically keeps doing so
        st["dscr_report_noise"] = np.exp(rng.normal(0.0, 0.13, n))

    # ── z-score anchors, fixed at origination so z stays comparable over time ─
    zs: dict[str, tuple[float, float]] = {}
    fallback = {"current_ltv": "original_ltv", "dscr": "dscr_orig"}
    for k in list(spec.numeric_betas) + list(spec.prepay_betas):
        if k in zs:
            continue
        if k == "interest_rate":
            zs[k] = _zstats(rate)
        elif k == "refi_incentive":
            zs[k] = (0.0, 1.5)                       # points of rate advantage
        else:
            src = attrs.get(k, attrs.get(fallback.get(k, "")))
            if src is None:
                raise KeyError(f"{spec.key}: no source for driver {k!r}")
            zs[k] = _zstats(np.asarray(src, dtype=float))

    lp_static = np.full(n, spec.intercept) + frailty
    for k, b in spec.numeric_betas.items():
        if k in attrs:
            m, s = zs[k]
            lp_static += b * (attrs[k] - m) / s
    for col, levels in spec.categorical_betas.items():
        eff = np.zeros(n)
        for lvl_, b in levels.items():
            eff[attrs[col] == lvl_] = b
        lp_static += eff

    lp_pp_static = np.full(n, spec.prepay_intercept)
    for k, b in spec.prepay_betas.items():
        if k in ("refi_incentive", "current_ltv", "dscr"):
            continue                                  # time-varying, added in loop
        src = rate if k == "interest_rate" else attrs.get(k)
        if src is not None:
            m, s = zs[k]
            lp_pp_static += b * (np.asarray(src, dtype=float) - m) / s

    # ── the monthly loop ─────────────────────────────────────────────────────
    rows: list[dict] = []
    thresh = spec.target.dpd_state

    for when in months:
        gi = midx[when]
        st["alive"] |= (~st["done"]) & (orig_i <= gi) & (orig_i >= 0)
        act = st["alive"] & (~st["done"])
        if not act.any():
            continue
        idx = np.flatnonzero(act)
        st["mob"][idx] = (gi - orig_i[idx]).astype(np.int32)

        now = {c: lvl[c][gi] for c in mev_raw.columns}
        znow = {c: float(zed[c][gi]) for c in mev_raw.columns}

        dyn: dict[str, np.ndarray] = {}
        if spec.dynamics is not None:
            sub = {k: (v[idx] if isinstance(v, np.ndarray) and v.shape[0] == n else v)
                   for k, v in st.items()}
            dyn = spec.dynamics(sub, now, None)

        lp = lp_static[idx] + seasoning_curve(st["mob"][idx].astype(float), *spec.seasoning)
        for k, b in spec.numeric_betas.items():
            if k in dyn:
                m, s = zs[k]
                lp = lp + b * (dyn[k] - m) / s
        for k, b in spec.mev_betas.items():
            lp = lp + b * znow[k]
        for it in spec.interactions:
            if it.level is not None:
                dv = (attrs[it.driver][idx] == it.level).astype(float)
            elif it.driver in dyn:
                m, s = zs[it.driver]
                dv = (dyn[it.driver] - m) / s
            else:
                m, s = zs[it.driver]
                dv = (attrs[it.driver][idx] - m) / s
            lp = lp + it.coef * dv * znow[it.mev]

        p_roll = _sigmoid(lp)
        d0 = st["delinq"][idx]
        u = rng.random(idx.size)

        new_state = d0.copy()
        cur = d0 == 0
        new_state[cur] = (u[cur] < p_roll[cur]).astype(np.int8)
        dq = d0 > 0
        if dq.any():
            p_fwd = np.clip(spec.roll_forward + 0.04 * (d0[dq] - 1), 0.05, 0.95)
            p_cure = np.clip(spec.cure_base * (0.62 ** (d0[dq] - 1)), 0.005, 0.90)
            ud = u[dq]
            new_state[dq] = np.where(ud < p_fwd, d0[dq] + 1,
                                     np.where(ud < p_fwd + p_cure, 0, d0[dq])).astype(np.int8)
        new_state = np.clip(new_state, 0, thresh).astype(np.int8)
        defaulted = new_state >= thresh

        lp_pp = lp_pp_static[idx].copy()
        if spec.key == "mortgage":
            inc = (rate[idx] * 100.0) - now["mortgage_rate"]
            m_, s_ = zs["refi_incentive"]
            lp_pp += spec.prepay_betas.get("refi_incentive", 0.0) * (inc - m_) / s_
        for k in ("current_ltv", "dscr"):
            if k in dyn and k in spec.prepay_betas:
                m_, s_ = zs[k]
                lp_pp += spec.prepay_betas[k] * (dyn[k] - m_) / s_
        prepaid = (~defaulted) & (new_state == 0) & (rng.random(idx.size) < _sigmoid(lp_pp))
        matured = (~defaulted) & (~prepaid) & (st["mob"][idx] >= term[idx])

        row = {
            "account_id": idx.astype(np.int32),
            "performance_date": np.full(idx.size, when),
            "months_on_book": st["mob"][idx],
            "current_balance": st["current_balance"][idx].astype(np.float32),
            "drawn_amount": st["drawn"][idx].astype(np.float32),
            "committed_amount_t": st["committed"][idx].astype(np.float32),
            "delinquency_state": new_state,
            "default_flag": defaulted.astype(np.int8),
            "prepaid_flag": prepaid.astype(np.int8),
            "matured_flag": matured.astype(np.int8),
            "_truth_roll_hazard": p_roll.astype(np.float32),
        }
        for k, v in dyn.items():
            row[k] = np.asarray(v, dtype=np.float32)
        rows.append(row)

        st["delinq"][idx] = new_state
        gone = defaulted | prepaid | matured
        st["done"][idx[gone]] = True

        live = idx[~gone]
        if live.size:
            paying = st["delinq"][live] == 0
            bal = st["current_balance"][live]
            interest = bal * r_m[live]
            princ = np.where(paying, np.maximum(pay[live] - interest, 0.0), 0.0)
            st["current_balance"][live] = np.maximum(
                bal - princ + np.where(paying, 0.0, interest), 0.0)
            if spec.key == "cre":
                rv = live[is_rev[live]]
                if rv.size:
                    # Revolvers draw down as they deteriorate. This is what makes
                    # the CCF genuinely estimable from the tape, not assumed.
                    stress = (st["delinq"][rv] > 0).astype(float)
                    tgt = st["util"][rv] + 0.075 * stress
                    if "dscr" in dyn:
                        pos = np.searchsorted(idx, rv)
                        tgt = tgt + 0.045 * (dyn["dscr"][pos] < 1.15)
                    st["util"][rv] = np.clip(
                        st["util"][rv] + 0.35 * (np.clip(tgt, 0.05, 1.0) - st["util"][rv]),
                        0.05, 1.0)
                    st["drawn"][rv] = st["committed"][rv] * st["util"][rv]
                    st["current_balance"][rv] = st["drawn"][rv]
            nr = live[~is_rev[live]]
            st["drawn"][nr] = st["current_balance"][nr]

    keys = list(rows[0])
    panel = pd.DataFrame({k: np.concatenate([r[k] for r in rows]) for k in keys})

    accounts = pd.DataFrame({
        "account_id": np.arange(n, dtype=np.int32),
        "origination_date": orig_date,
        "original_balance": orig_balance,
        "committed_amount": committed,
        "interest_rate": rate,
        "original_term": term,
        "scheduled_payment": pay,
        "_truth_frailty": frailty,
        **attrs,
    })
    accounts["vintage"] = pd.DatetimeIndex(accounts["origination_date"]).year
    return GenerationResult(panel=panel, accounts=accounts, spec=spec, mev_z=mev_z)
